package dev.iconpln.mims.data.local.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TDETAIL_PEMERIKSAAN_ULP".
 */
@Entity
public class TDetailPemeriksaanULP {

    @Id
    private Long id;
    private String NoMaterial;
    private String Spesifikasi;
    private String KuantitasPeriksa;
    private String Kuantitas;
    private String GudangAsal;
    private String SerialNumberScanned;
    private String IsDone;

    @Generated
    public TDetailPemeriksaanULP() {
    }

    public TDetailPemeriksaanULP(Long id) {
        this.id = id;
    }

    @Generated
    public TDetailPemeriksaanULP(Long id, String NoMaterial, String Spesifikasi, String KuantitasPeriksa, String Kuantitas, String GudangAsal, String SerialNumberScanned, String IsDone) {
        this.id = id;
        this.NoMaterial = NoMaterial;
        this.Spesifikasi = Spesifikasi;
        this.KuantitasPeriksa = KuantitasPeriksa;
        this.Kuantitas = Kuantitas;
        this.GudangAsal = GudangAsal;
        this.SerialNumberScanned = SerialNumberScanned;
        this.IsDone = IsDone;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNoMaterial() {
        return NoMaterial;
    }

    public void setNoMaterial(String NoMaterial) {
        this.NoMaterial = NoMaterial;
    }

    public String getSpesifikasi() {
        return Spesifikasi;
    }

    public void setSpesifikasi(String Spesifikasi) {
        this.Spesifikasi = Spesifikasi;
    }

    public String getKuantitasPeriksa() {
        return KuantitasPeriksa;
    }

    public void setKuantitasPeriksa(String KuantitasPeriksa) {
        this.KuantitasPeriksa = KuantitasPeriksa;
    }

    public String getKuantitas() {
        return Kuantitas;
    }

    public void setKuantitas(String Kuantitas) {
        this.Kuantitas = Kuantitas;
    }

    public String getGudangAsal() {
        return GudangAsal;
    }

    public void setGudangAsal(String GudangAsal) {
        this.GudangAsal = GudangAsal;
    }

    public String getSerialNumberScanned() {
        return SerialNumberScanned;
    }

    public void setSerialNumberScanned(String SerialNumberScanned) {
        this.SerialNumberScanned = SerialNumberScanned;
    }

    public String getIsDone() {
        return IsDone;
    }

    public void setIsDone(String IsDone) {
        this.IsDone = IsDone;
    }

}
