package dev.iconpln.mims.data.local.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TLIST_SN_MATERIAL_PENERIMAAN_ULP".
 */
@Entity
public class TListSnMaterialPenerimaanUlp {

    @Id
    private Long id;
    private String NoRepackaging;
    private String NoMaterial;
    private String NoSerialNumber;
    private String Status;
    private Integer IsScanned;

    @Generated
    public TListSnMaterialPenerimaanUlp() {
    }

    public TListSnMaterialPenerimaanUlp(Long id) {
        this.id = id;
    }

    @Generated
    public TListSnMaterialPenerimaanUlp(Long id, String NoRepackaging, String NoMaterial, String NoSerialNumber, String Status, Integer IsScanned) {
        this.id = id;
        this.NoRepackaging = NoRepackaging;
        this.NoMaterial = NoMaterial;
        this.NoSerialNumber = NoSerialNumber;
        this.Status = Status;
        this.IsScanned = IsScanned;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNoRepackaging() {
        return NoRepackaging;
    }

    public void setNoRepackaging(String NoRepackaging) {
        this.NoRepackaging = NoRepackaging;
    }

    public String getNoMaterial() {
        return NoMaterial;
    }

    public void setNoMaterial(String NoMaterial) {
        this.NoMaterial = NoMaterial;
    }

    public String getNoSerialNumber() {
        return NoSerialNumber;
    }

    public void setNoSerialNumber(String NoSerialNumber) {
        this.NoSerialNumber = NoSerialNumber;
    }

    public String getStatus() {
        return Status;
    }

    public void setStatus(String Status) {
        this.Status = Status;
    }

    public Integer getIsScanned() {
        return IsScanned;
    }

    public void setIsScanned(Integer IsScanned) {
        this.IsScanned = IsScanned;
    }

}
