package dev.iconpln.mims.data.local.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TLOKASI".
 */
@Entity
public class TLokasi {

    @Id
    private Long id;
    private String NoDoSns;
    private String Ket;
    private String UpdateDate;

    @Generated
    public TLokasi() {
    }

    public TLokasi(Long id) {
        this.id = id;
    }

    @Generated
    public TLokasi(Long id, String NoDoSns, String Ket, String UpdateDate) {
        this.id = id;
        this.NoDoSns = NoDoSns;
        this.Ket = Ket;
        this.UpdateDate = UpdateDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNoDoSns() {
        return NoDoSns;
    }

    public void setNoDoSns(String NoDoSns) {
        this.NoDoSns = NoDoSns;
    }

    public String getKet() {
        return Ket;
    }

    public void setKet(String Ket) {
        this.Ket = Ket;
    }

    public String getUpdateDate() {
        return UpdateDate;
    }

    public void setUpdateDate(String UpdateDate) {
        this.UpdateDate = UpdateDate;
    }

}
