package dev.iconpln.mims.data.local.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TMATERIAL".
 */
@Entity
public class TMaterial {

    @Id
    private Long id;
    private String NomorMaterial;
    private String Mmc;
    private String MaterialGroup;
    private String TglProduksi;
    private String NomorSertMaterologi;
    private String Storloc;
    private String Plant;
    private String MaterialId;
    private String MasaGaransi;
    private String NoProduksi;
    private String Tahun;
    private String NamaKategoriMaterial;
    private String KdPabrikan;

    @Generated
    public TMaterial() {
    }

    public TMaterial(Long id) {
        this.id = id;
    }

    @Generated
    public TMaterial(Long id, String NomorMaterial, String Mmc, String MaterialGroup, String TglProduksi, String NomorSertMaterologi, String Storloc, String Plant, String MaterialId, String MasaGaransi, String NoProduksi, String Tahun, String NamaKategoriMaterial, String KdPabrikan) {
        this.id = id;
        this.NomorMaterial = NomorMaterial;
        this.Mmc = Mmc;
        this.MaterialGroup = MaterialGroup;
        this.TglProduksi = TglProduksi;
        this.NomorSertMaterologi = NomorSertMaterologi;
        this.Storloc = Storloc;
        this.Plant = Plant;
        this.MaterialId = MaterialId;
        this.MasaGaransi = MasaGaransi;
        this.NoProduksi = NoProduksi;
        this.Tahun = Tahun;
        this.NamaKategoriMaterial = NamaKategoriMaterial;
        this.KdPabrikan = KdPabrikan;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNomorMaterial() {
        return NomorMaterial;
    }

    public void setNomorMaterial(String NomorMaterial) {
        this.NomorMaterial = NomorMaterial;
    }

    public String getMmc() {
        return Mmc;
    }

    public void setMmc(String Mmc) {
        this.Mmc = Mmc;
    }

    public String getMaterialGroup() {
        return MaterialGroup;
    }

    public void setMaterialGroup(String MaterialGroup) {
        this.MaterialGroup = MaterialGroup;
    }

    public String getTglProduksi() {
        return TglProduksi;
    }

    public void setTglProduksi(String TglProduksi) {
        this.TglProduksi = TglProduksi;
    }

    public String getNomorSertMaterologi() {
        return NomorSertMaterologi;
    }

    public void setNomorSertMaterologi(String NomorSertMaterologi) {
        this.NomorSertMaterologi = NomorSertMaterologi;
    }

    public String getStorloc() {
        return Storloc;
    }

    public void setStorloc(String Storloc) {
        this.Storloc = Storloc;
    }

    public String getPlant() {
        return Plant;
    }

    public void setPlant(String Plant) {
        this.Plant = Plant;
    }

    public String getMaterialId() {
        return MaterialId;
    }

    public void setMaterialId(String MaterialId) {
        this.MaterialId = MaterialId;
    }

    public String getMasaGaransi() {
        return MasaGaransi;
    }

    public void setMasaGaransi(String MasaGaransi) {
        this.MasaGaransi = MasaGaransi;
    }

    public String getNoProduksi() {
        return NoProduksi;
    }

    public void setNoProduksi(String NoProduksi) {
        this.NoProduksi = NoProduksi;
    }

    public String getTahun() {
        return Tahun;
    }

    public void setTahun(String Tahun) {
        this.Tahun = Tahun;
    }

    public String getNamaKategoriMaterial() {
        return NamaKategoriMaterial;
    }

    public void setNamaKategoriMaterial(String NamaKategoriMaterial) {
        this.NamaKategoriMaterial = NamaKategoriMaterial;
    }

    public String getKdPabrikan() {
        return KdPabrikan;
    }

    public void setKdPabrikan(String KdPabrikan) {
        this.KdPabrikan = KdPabrikan;
    }

}
