package dev.iconpln.mims.data.local.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TMONITORING".
 */
@Entity
public class TMonitoring {

    @Id
    private Long id;
    private String NomorMaterial;
    private String KdPabrikan;
    private String MatSapNo;
    private String StoreLoc;
    private String Uom;
    private String Unit;
    private String MaterialDesc;
    private String TlskNo;
    private String PoSapNo;
    private String PoMpNo;
    private String Qty;
    private String LeadTime;
    private String CreatedDate;

    @Generated
    public TMonitoring() {
    }

    public TMonitoring(Long id) {
        this.id = id;
    }

    @Generated
    public TMonitoring(Long id, String NomorMaterial, String KdPabrikan, String MatSapNo, String StoreLoc, String Uom, String Unit, String MaterialDesc, String TlskNo, String PoSapNo, String PoMpNo, String Qty, String LeadTime, String CreatedDate) {
        this.id = id;
        this.NomorMaterial = NomorMaterial;
        this.KdPabrikan = KdPabrikan;
        this.MatSapNo = MatSapNo;
        this.StoreLoc = StoreLoc;
        this.Uom = Uom;
        this.Unit = Unit;
        this.MaterialDesc = MaterialDesc;
        this.TlskNo = TlskNo;
        this.PoSapNo = PoSapNo;
        this.PoMpNo = PoMpNo;
        this.Qty = Qty;
        this.LeadTime = LeadTime;
        this.CreatedDate = CreatedDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNomorMaterial() {
        return NomorMaterial;
    }

    public void setNomorMaterial(String NomorMaterial) {
        this.NomorMaterial = NomorMaterial;
    }

    public String getKdPabrikan() {
        return KdPabrikan;
    }

    public void setKdPabrikan(String KdPabrikan) {
        this.KdPabrikan = KdPabrikan;
    }

    public String getMatSapNo() {
        return MatSapNo;
    }

    public void setMatSapNo(String MatSapNo) {
        this.MatSapNo = MatSapNo;
    }

    public String getStoreLoc() {
        return StoreLoc;
    }

    public void setStoreLoc(String StoreLoc) {
        this.StoreLoc = StoreLoc;
    }

    public String getUom() {
        return Uom;
    }

    public void setUom(String Uom) {
        this.Uom = Uom;
    }

    public String getUnit() {
        return Unit;
    }

    public void setUnit(String Unit) {
        this.Unit = Unit;
    }

    public String getMaterialDesc() {
        return MaterialDesc;
    }

    public void setMaterialDesc(String MaterialDesc) {
        this.MaterialDesc = MaterialDesc;
    }

    public String getTlskNo() {
        return TlskNo;
    }

    public void setTlskNo(String TlskNo) {
        this.TlskNo = TlskNo;
    }

    public String getPoSapNo() {
        return PoSapNo;
    }

    public void setPoSapNo(String PoSapNo) {
        this.PoSapNo = PoSapNo;
    }

    public String getPoMpNo() {
        return PoMpNo;
    }

    public void setPoMpNo(String PoMpNo) {
        this.PoMpNo = PoMpNo;
    }

    public String getQty() {
        return Qty;
    }

    public void setQty(String Qty) {
        this.Qty = Qty;
    }

    public String getLeadTime() {
        return LeadTime;
    }

    public void setLeadTime(String LeadTime) {
        this.LeadTime = LeadTime;
    }

    public String getCreatedDate() {
        return CreatedDate;
    }

    public void setCreatedDate(String CreatedDate) {
        this.CreatedDate = CreatedDate;
    }

}
