package dev.iconpln.mims.data.local.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TMONITORING_PERMINTAAN_DETAIL".
 */
@Entity
public class TMonitoringPermintaanDetail {

    @Id
    private Long id;
    private String NoPermintaan;
    private String NoRepackaging;
    private String NomorMaterial;
    private String Unit;
    private String QtyPermintaan;
    private String MaterialDesc;
    private String QtyScan;
    private String Kategori;
    private String QtyPengeluaran;

    @Generated
    public TMonitoringPermintaanDetail() {
    }

    public TMonitoringPermintaanDetail(Long id) {
        this.id = id;
    }

    @Generated
    public TMonitoringPermintaanDetail(Long id, String NoPermintaan, String NoRepackaging, String NomorMaterial, String Unit, String QtyPermintaan, String MaterialDesc, String QtyScan, String Kategori, String QtyPengeluaran) {
        this.id = id;
        this.NoPermintaan = NoPermintaan;
        this.NoRepackaging = NoRepackaging;
        this.NomorMaterial = NomorMaterial;
        this.Unit = Unit;
        this.QtyPermintaan = QtyPermintaan;
        this.MaterialDesc = MaterialDesc;
        this.QtyScan = QtyScan;
        this.Kategori = Kategori;
        this.QtyPengeluaran = QtyPengeluaran;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNoPermintaan() {
        return NoPermintaan;
    }

    public void setNoPermintaan(String NoPermintaan) {
        this.NoPermintaan = NoPermintaan;
    }

    public String getNoRepackaging() {
        return NoRepackaging;
    }

    public void setNoRepackaging(String NoRepackaging) {
        this.NoRepackaging = NoRepackaging;
    }

    public String getNomorMaterial() {
        return NomorMaterial;
    }

    public void setNomorMaterial(String NomorMaterial) {
        this.NomorMaterial = NomorMaterial;
    }

    public String getUnit() {
        return Unit;
    }

    public void setUnit(String Unit) {
        this.Unit = Unit;
    }

    public String getQtyPermintaan() {
        return QtyPermintaan;
    }

    public void setQtyPermintaan(String QtyPermintaan) {
        this.QtyPermintaan = QtyPermintaan;
    }

    public String getMaterialDesc() {
        return MaterialDesc;
    }

    public void setMaterialDesc(String MaterialDesc) {
        this.MaterialDesc = MaterialDesc;
    }

    public String getQtyScan() {
        return QtyScan;
    }

    public void setQtyScan(String QtyScan) {
        this.QtyScan = QtyScan;
    }

    public String getKategori() {
        return Kategori;
    }

    public void setKategori(String Kategori) {
        this.Kategori = Kategori;
    }

    public String getQtyPengeluaran() {
        return QtyPengeluaran;
    }

    public void setQtyPengeluaran(String QtyPengeluaran) {
        this.QtyPengeluaran = QtyPengeluaran;
    }

}
