package dev.iconpln.mims.data.local.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TMONITORING_PERMINTAAN_DETAIL".
 */
@Entity
public class TMonitoringPermintaanDetail {

    @Id
    private Long id;
    private String NoPermintaan;
    private String NoTransaksi;
    private String NoRepackaging;
    private String NomorMaterial;
    private String Unit;
    private Double QtyPermintaan;
    private String MaterialDesc;
    private Double QtyScan;
    private String Kategori;
    private Double QtyPengeluaran;
    private Boolean IsActive;

    @Generated
    public TMonitoringPermintaanDetail() {
    }

    public TMonitoringPermintaanDetail(Long id) {
        this.id = id;
    }

    @Generated
    public TMonitoringPermintaanDetail(Long id, String NoPermintaan, String NoTransaksi, String NoRepackaging, String NomorMaterial, String Unit, Double QtyPermintaan, String MaterialDesc, Double QtyScan, String Kategori, Double QtyPengeluaran, Boolean IsActive) {
        this.id = id;
        this.NoPermintaan = NoPermintaan;
        this.NoTransaksi = NoTransaksi;
        this.NoRepackaging = NoRepackaging;
        this.NomorMaterial = NomorMaterial;
        this.Unit = Unit;
        this.QtyPermintaan = QtyPermintaan;
        this.MaterialDesc = MaterialDesc;
        this.QtyScan = QtyScan;
        this.Kategori = Kategori;
        this.QtyPengeluaran = QtyPengeluaran;
        this.IsActive = IsActive;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNoPermintaan() {
        return NoPermintaan;
    }

    public void setNoPermintaan(String NoPermintaan) {
        this.NoPermintaan = NoPermintaan;
    }

    public String getNoTransaksi() {
        return NoTransaksi;
    }

    public void setNoTransaksi(String NoTransaksi) {
        this.NoTransaksi = NoTransaksi;
    }

    public String getNoRepackaging() {
        return NoRepackaging;
    }

    public void setNoRepackaging(String NoRepackaging) {
        this.NoRepackaging = NoRepackaging;
    }

    public String getNomorMaterial() {
        return NomorMaterial;
    }

    public void setNomorMaterial(String NomorMaterial) {
        this.NomorMaterial = NomorMaterial;
    }

    public String getUnit() {
        return Unit;
    }

    public void setUnit(String Unit) {
        this.Unit = Unit;
    }

    public Double getQtyPermintaan() {
        return QtyPermintaan;
    }

    public void setQtyPermintaan(Double QtyPermintaan) {
        this.QtyPermintaan = QtyPermintaan;
    }

    public String getMaterialDesc() {
        return MaterialDesc;
    }

    public void setMaterialDesc(String MaterialDesc) {
        this.MaterialDesc = MaterialDesc;
    }

    public Double getQtyScan() {
        return QtyScan;
    }

    public void setQtyScan(Double QtyScan) {
        this.QtyScan = QtyScan;
    }

    public String getKategori() {
        return Kategori;
    }

    public void setKategori(String Kategori) {
        this.Kategori = Kategori;
    }

    public Double getQtyPengeluaran() {
        return QtyPengeluaran;
    }

    public void setQtyPengeluaran(Double QtyPengeluaran) {
        this.QtyPengeluaran = QtyPengeluaran;
    }

    public Boolean getIsActive() {
        return IsActive;
    }

    public void setIsActive(Boolean IsActive) {
        this.IsActive = IsActive;
    }

}
