package dev.iconpln.mims.data.local.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TMONITORING_SN_MATERIAL".
 */
@Entity
public class TMonitoringSnMaterial {

    @Id
    private Long id;
    private String NoPermintaan;
    private String SnMaterial;
    private String IsScanned;

    @Generated
    public TMonitoringSnMaterial() {
    }

    public TMonitoringSnMaterial(Long id) {
        this.id = id;
    }

    @Generated
    public TMonitoringSnMaterial(Long id, String NoPermintaan, String SnMaterial, String IsScanned) {
        this.id = id;
        this.NoPermintaan = NoPermintaan;
        this.SnMaterial = SnMaterial;
        this.IsScanned = IsScanned;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNoPermintaan() {
        return NoPermintaan;
    }

    public void setNoPermintaan(String NoPermintaan) {
        this.NoPermintaan = NoPermintaan;
    }

    public String getSnMaterial() {
        return SnMaterial;
    }

    public void setSnMaterial(String SnMaterial) {
        this.SnMaterial = SnMaterial;
    }

    public String getIsScanned() {
        return IsScanned;
    }

    public void setIsScanned(String IsScanned) {
        this.IsScanned = IsScanned;
    }

}
