package dev.iconpln.mims.data.local.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TMONITORING_COMPLAINT_DETAIL".
 */
@Entity
public class TMonitoringComplaintDetail {

    @Id
    private Long id;
    private String NoMatSap;
    private String DoLineItem;
    private String TanggalPengajuan;
    private String NoPackaging;
    private String NoSerial;
    private String NoKomplain;
    private String Status;
    private String NoDoSmar;
    private String TanggalSelesai;
    private String StatusPeriksa;
    private String PartialCode;
    private Integer IsChecked;
    private Integer IsDone;

    @Generated
    public TMonitoringComplaintDetail() {
    }

    public TMonitoringComplaintDetail(Long id) {
        this.id = id;
    }

    @Generated
    public TMonitoringComplaintDetail(Long id, String NoMatSap, String DoLineItem, String TanggalPengajuan, String NoPackaging, String NoSerial, String NoKomplain, String Status, String NoDoSmar, String TanggalSelesai, String StatusPeriksa, String PartialCode, Integer IsChecked, Integer IsDone) {
        this.id = id;
        this.NoMatSap = NoMatSap;
        this.DoLineItem = DoLineItem;
        this.TanggalPengajuan = TanggalPengajuan;
        this.NoPackaging = NoPackaging;
        this.NoSerial = NoSerial;
        this.NoKomplain = NoKomplain;
        this.Status = Status;
        this.NoDoSmar = NoDoSmar;
        this.TanggalSelesai = TanggalSelesai;
        this.StatusPeriksa = StatusPeriksa;
        this.PartialCode = PartialCode;
        this.IsChecked = IsChecked;
        this.IsDone = IsDone;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNoMatSap() {
        return NoMatSap;
    }

    public void setNoMatSap(String NoMatSap) {
        this.NoMatSap = NoMatSap;
    }

    public String getDoLineItem() {
        return DoLineItem;
    }

    public void setDoLineItem(String DoLineItem) {
        this.DoLineItem = DoLineItem;
    }

    public String getTanggalPengajuan() {
        return TanggalPengajuan;
    }

    public void setTanggalPengajuan(String TanggalPengajuan) {
        this.TanggalPengajuan = TanggalPengajuan;
    }

    public String getNoPackaging() {
        return NoPackaging;
    }

    public void setNoPackaging(String NoPackaging) {
        this.NoPackaging = NoPackaging;
    }

    public String getNoSerial() {
        return NoSerial;
    }

    public void setNoSerial(String NoSerial) {
        this.NoSerial = NoSerial;
    }

    public String getNoKomplain() {
        return NoKomplain;
    }

    public void setNoKomplain(String NoKomplain) {
        this.NoKomplain = NoKomplain;
    }

    public String getStatus() {
        return Status;
    }

    public void setStatus(String Status) {
        this.Status = Status;
    }

    public String getNoDoSmar() {
        return NoDoSmar;
    }

    public void setNoDoSmar(String NoDoSmar) {
        this.NoDoSmar = NoDoSmar;
    }

    public String getTanggalSelesai() {
        return TanggalSelesai;
    }

    public void setTanggalSelesai(String TanggalSelesai) {
        this.TanggalSelesai = TanggalSelesai;
    }

    public String getStatusPeriksa() {
        return StatusPeriksa;
    }

    public void setStatusPeriksa(String StatusPeriksa) {
        this.StatusPeriksa = StatusPeriksa;
    }

    public String getPartialCode() {
        return PartialCode;
    }

    public void setPartialCode(String PartialCode) {
        this.PartialCode = PartialCode;
    }

    public Integer getIsChecked() {
        return IsChecked;
    }

    public void setIsChecked(Integer IsChecked) {
        this.IsChecked = IsChecked;
    }

    public Integer getIsDone() {
        return IsDone;
    }

    public void setIsDone(Integer IsDone) {
        this.IsDone = IsDone;
    }

}
