package dev.iconpln.mims.data.local.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TPEMAKAIAN_DETAIL".
 */
@Entity
public class TPemakaianDetail {

    @Id
    private Long id;
    private String NoTransaksi;
    private String NomorMaterial;
    private String NamaMaterial;
    private Double QtyReservasi;
    private Double QtyPemakaian;
    private Double QtyPengeluaran;
    private String Unit;
    private String NoMeter;
    private String ValuationType;
    private String Keterangan;
    private Boolean IsActive;

    @Generated
    public TPemakaianDetail() {
    }

    public TPemakaianDetail(Long id) {
        this.id = id;
    }

    @Generated
    public TPemakaianDetail(Long id, String NoTransaksi, String NomorMaterial, String NamaMaterial, Double QtyReservasi, Double QtyPemakaian, Double QtyPengeluaran, String Unit, String NoMeter, String ValuationType, String Keterangan, Boolean IsActive) {
        this.id = id;
        this.NoTransaksi = NoTransaksi;
        this.NomorMaterial = NomorMaterial;
        this.NamaMaterial = NamaMaterial;
        this.QtyReservasi = QtyReservasi;
        this.QtyPemakaian = QtyPemakaian;
        this.QtyPengeluaran = QtyPengeluaran;
        this.Unit = Unit;
        this.NoMeter = NoMeter;
        this.ValuationType = ValuationType;
        this.Keterangan = Keterangan;
        this.IsActive = IsActive;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNoTransaksi() {
        return NoTransaksi;
    }

    public void setNoTransaksi(String NoTransaksi) {
        this.NoTransaksi = NoTransaksi;
    }

    public String getNomorMaterial() {
        return NomorMaterial;
    }

    public void setNomorMaterial(String NomorMaterial) {
        this.NomorMaterial = NomorMaterial;
    }

    public String getNamaMaterial() {
        return NamaMaterial;
    }

    public void setNamaMaterial(String NamaMaterial) {
        this.NamaMaterial = NamaMaterial;
    }

    public Double getQtyReservasi() {
        return QtyReservasi;
    }

    public void setQtyReservasi(Double QtyReservasi) {
        this.QtyReservasi = QtyReservasi;
    }

    public Double getQtyPemakaian() {
        return QtyPemakaian;
    }

    public void setQtyPemakaian(Double QtyPemakaian) {
        this.QtyPemakaian = QtyPemakaian;
    }

    public Double getQtyPengeluaran() {
        return QtyPengeluaran;
    }

    public void setQtyPengeluaran(Double QtyPengeluaran) {
        this.QtyPengeluaran = QtyPengeluaran;
    }

    public String getUnit() {
        return Unit;
    }

    public void setUnit(String Unit) {
        this.Unit = Unit;
    }

    public String getNoMeter() {
        return NoMeter;
    }

    public void setNoMeter(String NoMeter) {
        this.NoMeter = NoMeter;
    }

    public String getValuationType() {
        return ValuationType;
    }

    public void setValuationType(String ValuationType) {
        this.ValuationType = ValuationType;
    }

    public String getKeterangan() {
        return Keterangan;
    }

    public void setKeterangan(String Keterangan) {
        this.Keterangan = Keterangan;
    }

    public Boolean getIsActive() {
        return IsActive;
    }

    public void setIsActive(Boolean IsActive) {
        this.IsActive = IsActive;
    }

}
