package dev.iconpln.mims.data.local.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TPENERIMAAN_DETAIL_ULP".
 */
@Entity
public class TPenerimaanDetailUlp {

    @Id
    private Long id;
    private String NoTransaksi;
    private String NoRepackaging;
    private String NoMaterial;
    private String MaterialDesc;
    private Double QtyPermintaan;
    private Double QtyPengiriman;
    private Double QtyPemeriksaan;
    private Double QtyPenerimaan;
    private Double QtySesuai;
    private Integer IsActive;

    @Generated
    public TPenerimaanDetailUlp() {
    }

    public TPenerimaanDetailUlp(Long id) {
        this.id = id;
    }

    @Generated
    public TPenerimaanDetailUlp(Long id, String NoTransaksi, String NoRepackaging, String NoMaterial, String MaterialDesc, Double QtyPermintaan, Double QtyPengiriman, Double QtyPemeriksaan, Double QtyPenerimaan, Double QtySesuai, Integer IsActive) {
        this.id = id;
        this.NoTransaksi = NoTransaksi;
        this.NoRepackaging = NoRepackaging;
        this.NoMaterial = NoMaterial;
        this.MaterialDesc = MaterialDesc;
        this.QtyPermintaan = QtyPermintaan;
        this.QtyPengiriman = QtyPengiriman;
        this.QtyPemeriksaan = QtyPemeriksaan;
        this.QtyPenerimaan = QtyPenerimaan;
        this.QtySesuai = QtySesuai;
        this.IsActive = IsActive;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNoTransaksi() {
        return NoTransaksi;
    }

    public void setNoTransaksi(String NoTransaksi) {
        this.NoTransaksi = NoTransaksi;
    }

    public String getNoRepackaging() {
        return NoRepackaging;
    }

    public void setNoRepackaging(String NoRepackaging) {
        this.NoRepackaging = NoRepackaging;
    }

    public String getNoMaterial() {
        return NoMaterial;
    }

    public void setNoMaterial(String NoMaterial) {
        this.NoMaterial = NoMaterial;
    }

    public String getMaterialDesc() {
        return MaterialDesc;
    }

    public void setMaterialDesc(String MaterialDesc) {
        this.MaterialDesc = MaterialDesc;
    }

    public Double getQtyPermintaan() {
        return QtyPermintaan;
    }

    public void setQtyPermintaan(Double QtyPermintaan) {
        this.QtyPermintaan = QtyPermintaan;
    }

    public Double getQtyPengiriman() {
        return QtyPengiriman;
    }

    public void setQtyPengiriman(Double QtyPengiriman) {
        this.QtyPengiriman = QtyPengiriman;
    }

    public Double getQtyPemeriksaan() {
        return QtyPemeriksaan;
    }

    public void setQtyPemeriksaan(Double QtyPemeriksaan) {
        this.QtyPemeriksaan = QtyPemeriksaan;
    }

    public Double getQtyPenerimaan() {
        return QtyPenerimaan;
    }

    public void setQtyPenerimaan(Double QtyPenerimaan) {
        this.QtyPenerimaan = QtyPenerimaan;
    }

    public Double getQtySesuai() {
        return QtySesuai;
    }

    public void setQtySesuai(Double QtySesuai) {
        this.QtySesuai = QtySesuai;
    }

    public Integer getIsActive() {
        return IsActive;
    }

    public void setIsActive(Integer IsActive) {
        this.IsActive = IsActive;
    }

}
