package dev.iconpln.mims.data.local.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TPENGUJIAN_DETAILS".
*/
public class TPengujianDetailsDao extends AbstractDao<TPengujianDetails, Long> {

    public static final String TABLENAME = "TPENGUJIAN_DETAILS";

    /**
     * Properties of entity TPengujianDetails.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SerialNumber = new Property(1, String.class, "SerialNumber", false, "SERIAL_NUMBER");
        public final static Property KeteranganMaterial = new Property(2, String.class, "KeteranganMaterial", false, "KETERANGAN_MATERIAL");
        public final static Property NoPengujian = new Property(3, String.class, "noPengujian", false, "NO_PENGUJIAN");
        public final static Property NamaKategori = new Property(4, String.class, "NamaKategori", false, "NAMA_KATEGORI");
        public final static Property StatusUji = new Property(5, String.class, "StatusUji", false, "STATUS_UJI");
    }


    public TPengujianDetailsDao(DaoConfig config) {
        super(config);
    }
    
    public TPengujianDetailsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TPENGUJIAN_DETAILS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"SERIAL_NUMBER\" TEXT," + // 1: SerialNumber
                "\"KETERANGAN_MATERIAL\" TEXT," + // 2: KeteranganMaterial
                "\"NO_PENGUJIAN\" TEXT," + // 3: noPengujian
                "\"NAMA_KATEGORI\" TEXT," + // 4: NamaKategori
                "\"STATUS_UJI\" TEXT);"); // 5: StatusUji
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TPENGUJIAN_DETAILS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TPengujianDetails entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String SerialNumber = entity.getSerialNumber();
        if (SerialNumber != null) {
            stmt.bindString(2, SerialNumber);
        }
 
        String KeteranganMaterial = entity.getKeteranganMaterial();
        if (KeteranganMaterial != null) {
            stmt.bindString(3, KeteranganMaterial);
        }
 
        String noPengujian = entity.getNoPengujian();
        if (noPengujian != null) {
            stmt.bindString(4, noPengujian);
        }
 
        String NamaKategori = entity.getNamaKategori();
        if (NamaKategori != null) {
            stmt.bindString(5, NamaKategori);
        }
 
        String StatusUji = entity.getStatusUji();
        if (StatusUji != null) {
            stmt.bindString(6, StatusUji);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TPengujianDetails entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String SerialNumber = entity.getSerialNumber();
        if (SerialNumber != null) {
            stmt.bindString(2, SerialNumber);
        }
 
        String KeteranganMaterial = entity.getKeteranganMaterial();
        if (KeteranganMaterial != null) {
            stmt.bindString(3, KeteranganMaterial);
        }
 
        String noPengujian = entity.getNoPengujian();
        if (noPengujian != null) {
            stmt.bindString(4, noPengujian);
        }
 
        String NamaKategori = entity.getNamaKategori();
        if (NamaKategori != null) {
            stmt.bindString(5, NamaKategori);
        }
 
        String StatusUji = entity.getStatusUji();
        if (StatusUji != null) {
            stmt.bindString(6, StatusUji);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TPengujianDetails readEntity(Cursor cursor, int offset) {
        TPengujianDetails entity = new TPengujianDetails( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // SerialNumber
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // KeteranganMaterial
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // noPengujian
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // NamaKategori
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // StatusUji
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TPengujianDetails entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSerialNumber(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setKeteranganMaterial(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setNoPengujian(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setNamaKategori(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setStatusUji(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TPengujianDetails entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TPengujianDetails entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TPengujianDetails entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
