package dev.iconpln.mims.data.local.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TPENGUJIAN_DETAILS".
 */
@Entity
public class TPengujianDetails {

    @Id
    private Long id;
    private String SerialNumber;
    private String KeteranganMaterial;
    private String noPengujian;
    private String NamaKategori;
    private String StatusUji;

    @Generated
    public TPengujianDetails() {
    }

    public TPengujianDetails(Long id) {
        this.id = id;
    }

    @Generated
    public TPengujianDetails(Long id, String SerialNumber, String KeteranganMaterial, String noPengujian, String NamaKategori, String StatusUji) {
        this.id = id;
        this.SerialNumber = SerialNumber;
        this.KeteranganMaterial = KeteranganMaterial;
        this.noPengujian = noPengujian;
        this.NamaKategori = NamaKategori;
        this.StatusUji = StatusUji;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSerialNumber() {
        return SerialNumber;
    }

    public void setSerialNumber(String SerialNumber) {
        this.SerialNumber = SerialNumber;
    }

    public String getKeteranganMaterial() {
        return KeteranganMaterial;
    }

    public void setKeteranganMaterial(String KeteranganMaterial) {
        this.KeteranganMaterial = KeteranganMaterial;
    }

    public String getNoPengujian() {
        return noPengujian;
    }

    public void setNoPengujian(String noPengujian) {
        this.noPengujian = noPengujian;
    }

    public String getNamaKategori() {
        return NamaKategori;
    }

    public void setNamaKategori(String NamaKategori) {
        this.NamaKategori = NamaKategori;
    }

    public String getStatusUji() {
        return StatusUji;
    }

    public void setStatusUji(String StatusUji) {
        this.StatusUji = StatusUji;
    }

}
