package dev.iconpln.mims.data.local.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TPENGUJIAN".
 */
@Entity
public class TPengujian {

    @Id
    private Long id;
    private String TanggalUji;
    private String NoPengujian;
    private String NamaKategori;
    private String QtyMaterial;
    private String QtySiap;
    private String Unit;
    private String StatusUji;
    private String KdPabrikan;

    @Generated
    public TPengujian() {
    }

    public TPengujian(Long id) {
        this.id = id;
    }

    @Generated
    public TPengujian(Long id, String TanggalUji, String NoPengujian, String NamaKategori, String QtyMaterial, String QtySiap, String Unit, String StatusUji, String KdPabrikan) {
        this.id = id;
        this.TanggalUji = TanggalUji;
        this.NoPengujian = NoPengujian;
        this.NamaKategori = NamaKategori;
        this.QtyMaterial = QtyMaterial;
        this.QtySiap = QtySiap;
        this.Unit = Unit;
        this.StatusUji = StatusUji;
        this.KdPabrikan = KdPabrikan;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTanggalUji() {
        return TanggalUji;
    }

    public void setTanggalUji(String TanggalUji) {
        this.TanggalUji = TanggalUji;
    }

    public String getNoPengujian() {
        return NoPengujian;
    }

    public void setNoPengujian(String NoPengujian) {
        this.NoPengujian = NoPengujian;
    }

    public String getNamaKategori() {
        return NamaKategori;
    }

    public void setNamaKategori(String NamaKategori) {
        this.NamaKategori = NamaKategori;
    }

    public String getQtyMaterial() {
        return QtyMaterial;
    }

    public void setQtyMaterial(String QtyMaterial) {
        this.QtyMaterial = QtyMaterial;
    }

    public String getQtySiap() {
        return QtySiap;
    }

    public void setQtySiap(String QtySiap) {
        this.QtySiap = QtySiap;
    }

    public String getUnit() {
        return Unit;
    }

    public void setUnit(String Unit) {
        this.Unit = Unit;
    }

    public String getStatusUji() {
        return StatusUji;
    }

    public void setStatusUji(String StatusUji) {
        this.StatusUji = StatusUji;
    }

    public String getKdPabrikan() {
        return KdPabrikan;
    }

    public void setKdPabrikan(String KdPabrikan) {
        this.KdPabrikan = KdPabrikan;
    }

}
