package dev.iconpln.mims.data.local.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TPOS_SNS".
 */
@Entity
public class TPosSns {

    @Id
    private Long id;
    private String noMatSap;
    private String Mmc;
    private String MaterialGroup;
    private String TglProduksi;
    private String KdPabrikan;
    private String NoSertMeterologi;
    private String Spln;
    private String NoProduksi;
    private String StorLoc;
    private String NamaKategoriMaterial;
    private String NoSerial;
    private String NoDoSmar;
    private String Spesifikasi;
    private String Plant;
    private String MaterialId;
    private String MasaGaransi;
    private String DoStatus;
    private String NoPackaging;
    private String Status;

    @Generated
    public TPosSns() {
    }

    public TPosSns(Long id) {
        this.id = id;
    }

    @Generated
    public TPosSns(Long id, String noMatSap, String Mmc, String MaterialGroup, String TglProduksi, String KdPabrikan, String NoSertMeterologi, String Spln, String NoProduksi, String StorLoc, String NamaKategoriMaterial, String NoSerial, String NoDoSmar, String Spesifikasi, String Plant, String MaterialId, String MasaGaransi, String DoStatus, String NoPackaging, String Status) {
        this.id = id;
        this.noMatSap = noMatSap;
        this.Mmc = Mmc;
        this.MaterialGroup = MaterialGroup;
        this.TglProduksi = TglProduksi;
        this.KdPabrikan = KdPabrikan;
        this.NoSertMeterologi = NoSertMeterologi;
        this.Spln = Spln;
        this.NoProduksi = NoProduksi;
        this.StorLoc = StorLoc;
        this.NamaKategoriMaterial = NamaKategoriMaterial;
        this.NoSerial = NoSerial;
        this.NoDoSmar = NoDoSmar;
        this.Spesifikasi = Spesifikasi;
        this.Plant = Plant;
        this.MaterialId = MaterialId;
        this.MasaGaransi = MasaGaransi;
        this.DoStatus = DoStatus;
        this.NoPackaging = NoPackaging;
        this.Status = Status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNoMatSap() {
        return noMatSap;
    }

    public void setNoMatSap(String noMatSap) {
        this.noMatSap = noMatSap;
    }

    public String getMmc() {
        return Mmc;
    }

    public void setMmc(String Mmc) {
        this.Mmc = Mmc;
    }

    public String getMaterialGroup() {
        return MaterialGroup;
    }

    public void setMaterialGroup(String MaterialGroup) {
        this.MaterialGroup = MaterialGroup;
    }

    public String getTglProduksi() {
        return TglProduksi;
    }

    public void setTglProduksi(String TglProduksi) {
        this.TglProduksi = TglProduksi;
    }

    public String getKdPabrikan() {
        return KdPabrikan;
    }

    public void setKdPabrikan(String KdPabrikan) {
        this.KdPabrikan = KdPabrikan;
    }

    public String getNoSertMeterologi() {
        return NoSertMeterologi;
    }

    public void setNoSertMeterologi(String NoSertMeterologi) {
        this.NoSertMeterologi = NoSertMeterologi;
    }

    public String getSpln() {
        return Spln;
    }

    public void setSpln(String Spln) {
        this.Spln = Spln;
    }

    public String getNoProduksi() {
        return NoProduksi;
    }

    public void setNoProduksi(String NoProduksi) {
        this.NoProduksi = NoProduksi;
    }

    public String getStorLoc() {
        return StorLoc;
    }

    public void setStorLoc(String StorLoc) {
        this.StorLoc = StorLoc;
    }

    public String getNamaKategoriMaterial() {
        return NamaKategoriMaterial;
    }

    public void setNamaKategoriMaterial(String NamaKategoriMaterial) {
        this.NamaKategoriMaterial = NamaKategoriMaterial;
    }

    public String getNoSerial() {
        return NoSerial;
    }

    public void setNoSerial(String NoSerial) {
        this.NoSerial = NoSerial;
    }

    public String getNoDoSmar() {
        return NoDoSmar;
    }

    public void setNoDoSmar(String NoDoSmar) {
        this.NoDoSmar = NoDoSmar;
    }

    public String getSpesifikasi() {
        return Spesifikasi;
    }

    public void setSpesifikasi(String Spesifikasi) {
        this.Spesifikasi = Spesifikasi;
    }

    public String getPlant() {
        return Plant;
    }

    public void setPlant(String Plant) {
        this.Plant = Plant;
    }

    public String getMaterialId() {
        return MaterialId;
    }

    public void setMaterialId(String MaterialId) {
        this.MaterialId = MaterialId;
    }

    public String getMasaGaransi() {
        return MasaGaransi;
    }

    public void setMasaGaransi(String MasaGaransi) {
        this.MasaGaransi = MasaGaransi;
    }

    public String getDoStatus() {
        return DoStatus;
    }

    public void setDoStatus(String DoStatus) {
        this.DoStatus = DoStatus;
    }

    public String getNoPackaging() {
        return NoPackaging;
    }

    public void setNoPackaging(String NoPackaging) {
        this.NoPackaging = NoPackaging;
    }

    public String getStatus() {
        return Status;
    }

    public void setStatus(String Status) {
        this.Status = Status;
    }

}
