package dev.iconpln.mims.data.local.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TPOS_DETAIL_PENERIMAAN".
 */
@Entity
public class TPosDetailPenerimaan {

    @Id
    private Long id;
    private String NoDoSmar;
    private String Qty;
    private String KdPabrikan;
    private String DoStatus;
    private String NoPackaging;
    private String SerialNumber;
    private String NoMaterial;
    private String NamaKategoriMaterial;
    private String StorLoc;
    private String StatusPenerimaan;
    private String StatusPemeriksaan;
    private Integer IsComplaint;
    private Integer IsChecked;
    private String DoLineItem;
    private String PartialCode;
    private Integer IsDone;

    @Generated
    public TPosDetailPenerimaan() {
    }

    public TPosDetailPenerimaan(Long id) {
        this.id = id;
    }

    @Generated
    public TPosDetailPenerimaan(Long id, String NoDoSmar, String Qty, String KdPabrikan, String DoStatus, String NoPackaging, String SerialNumber, String NoMaterial, String NamaKategoriMaterial, String StorLoc, String StatusPenerimaan, String StatusPemeriksaan, Integer IsComplaint, Integer IsChecked, String DoLineItem, String PartialCode, Integer IsDone) {
        this.id = id;
        this.NoDoSmar = NoDoSmar;
        this.Qty = Qty;
        this.KdPabrikan = KdPabrikan;
        this.DoStatus = DoStatus;
        this.NoPackaging = NoPackaging;
        this.SerialNumber = SerialNumber;
        this.NoMaterial = NoMaterial;
        this.NamaKategoriMaterial = NamaKategoriMaterial;
        this.StorLoc = StorLoc;
        this.StatusPenerimaan = StatusPenerimaan;
        this.StatusPemeriksaan = StatusPemeriksaan;
        this.IsComplaint = IsComplaint;
        this.IsChecked = IsChecked;
        this.DoLineItem = DoLineItem;
        this.PartialCode = PartialCode;
        this.IsDone = IsDone;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNoDoSmar() {
        return NoDoSmar;
    }

    public void setNoDoSmar(String NoDoSmar) {
        this.NoDoSmar = NoDoSmar;
    }

    public String getQty() {
        return Qty;
    }

    public void setQty(String Qty) {
        this.Qty = Qty;
    }

    public String getKdPabrikan() {
        return KdPabrikan;
    }

    public void setKdPabrikan(String KdPabrikan) {
        this.KdPabrikan = KdPabrikan;
    }

    public String getDoStatus() {
        return DoStatus;
    }

    public void setDoStatus(String DoStatus) {
        this.DoStatus = DoStatus;
    }

    public String getNoPackaging() {
        return NoPackaging;
    }

    public void setNoPackaging(String NoPackaging) {
        this.NoPackaging = NoPackaging;
    }

    public String getSerialNumber() {
        return SerialNumber;
    }

    public void setSerialNumber(String SerialNumber) {
        this.SerialNumber = SerialNumber;
    }

    public String getNoMaterial() {
        return NoMaterial;
    }

    public void setNoMaterial(String NoMaterial) {
        this.NoMaterial = NoMaterial;
    }

    public String getNamaKategoriMaterial() {
        return NamaKategoriMaterial;
    }

    public void setNamaKategoriMaterial(String NamaKategoriMaterial) {
        this.NamaKategoriMaterial = NamaKategoriMaterial;
    }

    public String getStorLoc() {
        return StorLoc;
    }

    public void setStorLoc(String StorLoc) {
        this.StorLoc = StorLoc;
    }

    public String getStatusPenerimaan() {
        return StatusPenerimaan;
    }

    public void setStatusPenerimaan(String StatusPenerimaan) {
        this.StatusPenerimaan = StatusPenerimaan;
    }

    public String getStatusPemeriksaan() {
        return StatusPemeriksaan;
    }

    public void setStatusPemeriksaan(String StatusPemeriksaan) {
        this.StatusPemeriksaan = StatusPemeriksaan;
    }

    public Integer getIsComplaint() {
        return IsComplaint;
    }

    public void setIsComplaint(Integer IsComplaint) {
        this.IsComplaint = IsComplaint;
    }

    public Integer getIsChecked() {
        return IsChecked;
    }

    public void setIsChecked(Integer IsChecked) {
        this.IsChecked = IsChecked;
    }

    public String getDoLineItem() {
        return DoLineItem;
    }

    public void setDoLineItem(String DoLineItem) {
        this.DoLineItem = DoLineItem;
    }

    public String getPartialCode() {
        return PartialCode;
    }

    public void setPartialCode(String PartialCode) {
        this.PartialCode = PartialCode;
    }

    public Integer getIsDone() {
        return IsDone;
    }

    public void setIsDone(Integer IsDone) {
        this.IsDone = IsDone;
    }

}
