package dev.iconpln.mims.data.local.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TPOS".
 */
@Entity
public class TPos {

    @Id
    private Long id;
    private String StorLoc;
    private String Total;
    private String TlskNo;
    private String PoSapNo;
    private String PoMpNo;
    private String NoDoSmar;
    private Integer LeadTime;
    private String Storloc;
    private String CreatedDate;
    private String PlanCodeNo;
    private String PlantName;
    private String NoDoMims;
    private String DoStatus;
    private String Expeditions;
    private String CourierPersonName;
    private String KdPabrikan;
    private String MaterialGroup;
    private String NamaKategoriMaterial;

    @Generated
    public TPos() {
    }

    public TPos(Long id) {
        this.id = id;
    }

    @Generated
    public TPos(Long id, String StorLoc, String Total, String TlskNo, String PoSapNo, String PoMpNo, String NoDoSmar, Integer LeadTime, String Storloc, String CreatedDate, String PlanCodeNo, String PlantName, String NoDoMims, String DoStatus, String Expeditions, String CourierPersonName, String KdPabrikan, String MaterialGroup, String NamaKategoriMaterial) {
        this.id = id;
        this.StorLoc = StorLoc;
        this.Total = Total;
        this.TlskNo = TlskNo;
        this.PoSapNo = PoSapNo;
        this.PoMpNo = PoMpNo;
        this.NoDoSmar = NoDoSmar;
        this.LeadTime = LeadTime;
        this.Storloc = Storloc;
        this.CreatedDate = CreatedDate;
        this.PlanCodeNo = PlanCodeNo;
        this.PlantName = PlantName;
        this.NoDoMims = NoDoMims;
        this.DoStatus = DoStatus;
        this.Expeditions = Expeditions;
        this.CourierPersonName = CourierPersonName;
        this.KdPabrikan = KdPabrikan;
        this.MaterialGroup = MaterialGroup;
        this.NamaKategoriMaterial = NamaKategoriMaterial;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getStorLoc() {
        return StorLoc;
    }

    public void setStorLoc(String StorLoc) {
        this.StorLoc = StorLoc;
    }

    public String getTotal() {
        return Total;
    }

    public void setTotal(String Total) {
        this.Total = Total;
    }

    public String getTlskNo() {
        return TlskNo;
    }

    public void setTlskNo(String TlskNo) {
        this.TlskNo = TlskNo;
    }

    public String getPoSapNo() {
        return PoSapNo;
    }

    public void setPoSapNo(String PoSapNo) {
        this.PoSapNo = PoSapNo;
    }

    public String getPoMpNo() {
        return PoMpNo;
    }

    public void setPoMpNo(String PoMpNo) {
        this.PoMpNo = PoMpNo;
    }

    public String getNoDoSmar() {
        return NoDoSmar;
    }

    public void setNoDoSmar(String NoDoSmar) {
        this.NoDoSmar = NoDoSmar;
    }

    public Integer getLeadTime() {
        return LeadTime;
    }

    public void setLeadTime(Integer LeadTime) {
        this.LeadTime = LeadTime;
    }

    public String getStorloc() {
        return Storloc;
    }

    public void setStorloc(String Storloc) {
        this.Storloc = Storloc;
    }

    public String getCreatedDate() {
        return CreatedDate;
    }

    public void setCreatedDate(String CreatedDate) {
        this.CreatedDate = CreatedDate;
    }

    public String getPlanCodeNo() {
        return PlanCodeNo;
    }

    public void setPlanCodeNo(String PlanCodeNo) {
        this.PlanCodeNo = PlanCodeNo;
    }

    public String getPlantName() {
        return PlantName;
    }

    public void setPlantName(String PlantName) {
        this.PlantName = PlantName;
    }

    public String getNoDoMims() {
        return NoDoMims;
    }

    public void setNoDoMims(String NoDoMims) {
        this.NoDoMims = NoDoMims;
    }

    public String getDoStatus() {
        return DoStatus;
    }

    public void setDoStatus(String DoStatus) {
        this.DoStatus = DoStatus;
    }

    public String getExpeditions() {
        return Expeditions;
    }

    public void setExpeditions(String Expeditions) {
        this.Expeditions = Expeditions;
    }

    public String getCourierPersonName() {
        return CourierPersonName;
    }

    public void setCourierPersonName(String CourierPersonName) {
        this.CourierPersonName = CourierPersonName;
    }

    public String getKdPabrikan() {
        return KdPabrikan;
    }

    public void setKdPabrikan(String KdPabrikan) {
        this.KdPabrikan = KdPabrikan;
    }

    public String getMaterialGroup() {
        return MaterialGroup;
    }

    public void setMaterialGroup(String MaterialGroup) {
        this.MaterialGroup = MaterialGroup;
    }

    public String getNamaKategoriMaterial() {
        return NamaKategoriMaterial;
    }

    public void setNamaKategoriMaterial(String NamaKategoriMaterial) {
        this.NamaKategoriMaterial = NamaKategoriMaterial;
    }

}
