package dev.iconpln.mims.data.local.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TPOS_DETAIL_PENERIMAAN_AKHIR".
*/
public class TPosDetailPenerimaanAkhirDao extends AbstractDao<TPosDetailPenerimaanAkhir, Long> {

    public static final String TABLENAME = "TPOS_DETAIL_PENERIMAAN_AKHIR";

    /**
     * Properties of entity TPosDetailPenerimaanAkhir.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property NoDoSmar = new Property(1, String.class, "NoDoSmar", false, "NO_DO_SMAR");
        public final static Property Qty = new Property(2, String.class, "Qty", false, "QTY");
        public final static Property KdPabrikan = new Property(3, String.class, "KdPabrikan", false, "KD_PABRIKAN");
        public final static Property NoPackaging = new Property(4, String.class, "NoPackaging", false, "NO_PACKAGING");
        public final static Property SerialNumber = new Property(5, String.class, "SerialNumber", false, "SERIAL_NUMBER");
        public final static Property NoMaterial = new Property(6, String.class, "NoMaterial", false, "NO_MATERIAL");
        public final static Property NamaKategoriMaterial = new Property(7, String.class, "NamaKategoriMaterial", false, "NAMA_KATEGORI_MATERIAL");
        public final static Property StorLoc = new Property(8, String.class, "StorLoc", false, "STOR_LOC");
        public final static Property IsComplaint = new Property(9, Boolean.class, "IsComplaint", false, "IS_COMPLAINT");
        public final static Property IsReceived = new Property(10, Boolean.class, "IsReceived", false, "IS_RECEIVED");
        public final static Property IsRejected = new Property(11, Boolean.class, "IsRejected", false, "IS_REJECTED");
    }


    public TPosDetailPenerimaanAkhirDao(DaoConfig config) {
        super(config);
    }
    
    public TPosDetailPenerimaanAkhirDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TPOS_DETAIL_PENERIMAAN_AKHIR\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NO_DO_SMAR\" TEXT," + // 1: NoDoSmar
                "\"QTY\" TEXT," + // 2: Qty
                "\"KD_PABRIKAN\" TEXT," + // 3: KdPabrikan
                "\"NO_PACKAGING\" TEXT," + // 4: NoPackaging
                "\"SERIAL_NUMBER\" TEXT," + // 5: SerialNumber
                "\"NO_MATERIAL\" TEXT," + // 6: NoMaterial
                "\"NAMA_KATEGORI_MATERIAL\" TEXT," + // 7: NamaKategoriMaterial
                "\"STOR_LOC\" TEXT," + // 8: StorLoc
                "\"IS_COMPLAINT\" INTEGER," + // 9: IsComplaint
                "\"IS_RECEIVED\" INTEGER," + // 10: IsReceived
                "\"IS_REJECTED\" INTEGER);"); // 11: IsRejected
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TPOS_DETAIL_PENERIMAAN_AKHIR\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TPosDetailPenerimaanAkhir entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String NoDoSmar = entity.getNoDoSmar();
        if (NoDoSmar != null) {
            stmt.bindString(2, NoDoSmar);
        }
 
        String Qty = entity.getQty();
        if (Qty != null) {
            stmt.bindString(3, Qty);
        }
 
        String KdPabrikan = entity.getKdPabrikan();
        if (KdPabrikan != null) {
            stmt.bindString(4, KdPabrikan);
        }
 
        String NoPackaging = entity.getNoPackaging();
        if (NoPackaging != null) {
            stmt.bindString(5, NoPackaging);
        }
 
        String SerialNumber = entity.getSerialNumber();
        if (SerialNumber != null) {
            stmt.bindString(6, SerialNumber);
        }
 
        String NoMaterial = entity.getNoMaterial();
        if (NoMaterial != null) {
            stmt.bindString(7, NoMaterial);
        }
 
        String NamaKategoriMaterial = entity.getNamaKategoriMaterial();
        if (NamaKategoriMaterial != null) {
            stmt.bindString(8, NamaKategoriMaterial);
        }
 
        String StorLoc = entity.getStorLoc();
        if (StorLoc != null) {
            stmt.bindString(9, StorLoc);
        }
 
        Boolean IsComplaint = entity.getIsComplaint();
        if (IsComplaint != null) {
            stmt.bindLong(10, IsComplaint ? 1L: 0L);
        }
 
        Boolean IsReceived = entity.getIsReceived();
        if (IsReceived != null) {
            stmt.bindLong(11, IsReceived ? 1L: 0L);
        }
 
        Boolean IsRejected = entity.getIsRejected();
        if (IsRejected != null) {
            stmt.bindLong(12, IsRejected ? 1L: 0L);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TPosDetailPenerimaanAkhir entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String NoDoSmar = entity.getNoDoSmar();
        if (NoDoSmar != null) {
            stmt.bindString(2, NoDoSmar);
        }
 
        String Qty = entity.getQty();
        if (Qty != null) {
            stmt.bindString(3, Qty);
        }
 
        String KdPabrikan = entity.getKdPabrikan();
        if (KdPabrikan != null) {
            stmt.bindString(4, KdPabrikan);
        }
 
        String NoPackaging = entity.getNoPackaging();
        if (NoPackaging != null) {
            stmt.bindString(5, NoPackaging);
        }
 
        String SerialNumber = entity.getSerialNumber();
        if (SerialNumber != null) {
            stmt.bindString(6, SerialNumber);
        }
 
        String NoMaterial = entity.getNoMaterial();
        if (NoMaterial != null) {
            stmt.bindString(7, NoMaterial);
        }
 
        String NamaKategoriMaterial = entity.getNamaKategoriMaterial();
        if (NamaKategoriMaterial != null) {
            stmt.bindString(8, NamaKategoriMaterial);
        }
 
        String StorLoc = entity.getStorLoc();
        if (StorLoc != null) {
            stmt.bindString(9, StorLoc);
        }
 
        Boolean IsComplaint = entity.getIsComplaint();
        if (IsComplaint != null) {
            stmt.bindLong(10, IsComplaint ? 1L: 0L);
        }
 
        Boolean IsReceived = entity.getIsReceived();
        if (IsReceived != null) {
            stmt.bindLong(11, IsReceived ? 1L: 0L);
        }
 
        Boolean IsRejected = entity.getIsRejected();
        if (IsRejected != null) {
            stmt.bindLong(12, IsRejected ? 1L: 0L);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TPosDetailPenerimaanAkhir readEntity(Cursor cursor, int offset) {
        TPosDetailPenerimaanAkhir entity = new TPosDetailPenerimaanAkhir( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // NoDoSmar
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // Qty
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // KdPabrikan
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // NoPackaging
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // SerialNumber
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // NoMaterial
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // NamaKategoriMaterial
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // StorLoc
            cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0, // IsComplaint
            cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0, // IsReceived
            cursor.isNull(offset + 11) ? null : cursor.getShort(offset + 11) != 0 // IsRejected
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TPosDetailPenerimaanAkhir entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNoDoSmar(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setQty(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setKdPabrikan(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setNoPackaging(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSerialNumber(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setNoMaterial(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setNamaKategoriMaterial(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setStorLoc(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setIsComplaint(cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0);
        entity.setIsReceived(cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0);
        entity.setIsRejected(cursor.isNull(offset + 11) ? null : cursor.getShort(offset + 11) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TPosDetailPenerimaanAkhir entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TPosDetailPenerimaanAkhir entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TPosDetailPenerimaanAkhir entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
